### ISSUE TITLE
error "sh: line 1: tsx: command not found"

### ISSUE THREAD

**Issue by AGenchev** [jehna/humanify#23]
I cloned the repo, installed npm, performed npm install and used this stanza to test it:
`npm start -- --local -o deobfuscated.js obfuscated-file.js`

unfortunately it cannot find sth called tsx.
What didn't work:
npm install --save-dev ts-node typescript
npm install tsx

I'm not much familiar w node.js.

**Comment by jehna** [comment]
Did you run just plain `npm install`? Please check the readme for getting started instructions

**Comment by AGenchev** [comment]
yes, I did npm install. I'll reboot and test again.

**Comment by AGenchev** [comment]
but, to have done it all, I installed conda and ran:
`conda env create -f environment.yaml`
The result is "Could not solve for environment specs".

**Comment by 0xdevalias** [comment]
`tsx` is in the `package.json` `dependencies`, so it should be installed properly with a `npm install`:

https://github.com/jehna/humanify/blob/002fd68d10f7ff13b80b7c305ad09c9c7f63bc47/package.json#L24

As a test, I added a new `which-tsx` script:

```diff
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "tsx src/index.ts",
+   "which-tsx": "which tsx"
  },
```

And ran it like this (on macOS):

```
⇒ npm run which-tsx
/Users/devalias/dev/tmp/humanify/node_modules/.bin/tsx
```

I would expect yours should show something similar; and if not, then perhaps you have some issues with how your environment `PATH` / node / similar is setup?

What OS / node version / etc are you running?

**Comment by AGenchev** [comment]
it seems your changes are not in the main branch, because git pull says it's up to date. I edited manually package.json to add ""which-tsx": "which tsx"".
Then
`"npm run which-tsx`
returns empty line. 

OS: Arch Linux;
`npm --version`
10.8.2
`node --version`
v22.5.1
`conda --version`
conda 24.5.0

**Comment by 0xdevalias** [comment]
> it seems your changes are not in the main branch, because git pull says it's up to date

@AGenchev I made the changes locally as a PoC/debug step; they were never intended to be comitted/pushed anywhere.

> especially these which conda can't find

`tsx` has nothing to do with python/conda; it's purely a node thing.

> I guess, on my computer npm is somewhat broken and doesn't install the packages which are required

It seems like that might be the case, and would be the area I would be looking to debug things further. It might be worth starting by looking of the `tsx` package is properly installed in the `./node_modules/` directory after `npm install`. And also maybe check what paths are included in your `PATH` env.

Beyond that, might be a bit beyond the type of support that can easily be provided on this repo, as it sounds like it may be more of an environment setup issue rather than an issue with this project.

**Comment by AGenchev** [comment]
Thanks, I was able to resolve this problem, which likely is related to the node version used: 
- removed the npm package from OS repo
- discovered that **nvm** (Node Version Manager) exists and installed it
- installed older nodejs (version 20)
- erased local copy  and cloned again the repo
- npm install worked.

So this problem is solved. 

`conda env create -f environment.yaml `
still fails, but this is not the topic here, so I close this. 
Thank you all for assisting with this issue.
